Objective

Integrate the machine learning components developed in previous days and translate their results into actionable business insights and recommendations.

Key Tasks

Review existing datasets, models, and generated outputs.
Integrate customer and restaurant segmentation, sentiment analysis, delivery time prediction, and hourly demand forecasting.
Summarize model performance and key findings.
Develop business insights and data-backed recommendations.
Document model limitations and future improvements.

In [1]:
from pathlib import Path

project_path = Path.cwd()

print("Current working directory:", project_path)
print("\nFiles and folders available:")

for item in sorted(project_path.iterdir()):
    print(item.name)

Current working directory: /home/nineleaps/Downloads/Uber_Eats_Operational_Intelligence/notebooks

Files and folders available:
day2_customer_restaurant_segmentation.ipynb
day3_CustomerFeedback_SentimentAnalysis.ipynb
day4_delivery_time_prediction.ipynb
day5_hourly_demand_forecasting.ipynb
day6_end_to_end_ml_pipeline.ipynb

In [2]:
from pathlib import Path

project_path = Path.cwd().parent

print("Project folder:", project_path)

for folder in ["data", "models", "outputs", "src", "docs"]:
    folder_path = project_path / folder

    if folder_path.exists():
        print(f"\n{folder}/")
        for item in sorted(folder_path.iterdir()):
            print("  ", item.name)
    else:
        print(f"\n{folder}/ - Folder not found")

Project folder: /home/nineleaps/Downloads/Uber_Eats_Operational_Intelligence

data/
   processed
   raw

models/
   day4_best_delivery_time_model.pkl
   day4_delivery_time_preprocessor.pkl
   delivery_time_linear_regression.pkl
   delivery_time_preprocessor.pkl

outputs/
   day4_cross_validation_results.csv
   day4_feature_engineered_dataset.csv
   day4_feature_importance.csv
   day4_final_recommendation.csv
   day4_model_comparison.csv
   day4_project_summary.csv
   day5_adf_results.csv
   day5_business_summary.csv
   day5_decomposition_components.csv
   day5_final_demand_forecast.csv
   day5_hourly_demand.csv
   day5_model_comparison.csv
   day5_test_predictions.csv
   day5_train_test_split.csv
   visualizations

src/
   generate_data.py
   validate_data.py

docs/
   data_dictionary.md

In [4]:
from pathlib import Path

project_path = Path.cwd().parent

for folder in ["data/raw", "data/processed", "models", "outputs", "src", "docs"]:
    folder_path = project_path / folder

    print(f"\n{'=' * 15} {folder} {'=' * 15}")

    if folder_path.exists():
        files = sorted(folder_path.rglob("*"))

        for file in files:
            if file.is_file():
                print(file.relative_to(project_path))
    else:
        print("Folder not found")

=============== data/raw ===============
data/raw/customers.csv
data/raw/deliveries.csv
data/raw/drivers.csv
data/raw/orders.csv
data/raw/payments.csv
data/raw/restaurants.csv
data/raw/reviews.csv

=============== data/processed ===============
data/processed/categorized_customer_complaints.csv
data/processed/cleaned_reviews.csv
data/processed/complaint_category_summary.csv
data/processed/customer_segments.csv
data/processed/day5_cleaned_orders.csv
data/processed/naive_bayes_sentiment_model.pkl
data/processed/restaurant_segments.csv
data/processed/reviews_tfidf.npz
data/processed/reviews_with_sentiment_analysis.csv
data/processed/sentiment_summary.csv
data/processed/svm_sentiment_model.pkl
data/processed/tfidf_vectorizer.pkl

=============== models ===============
models/day4_best_delivery_time_model.pkl
models/day4_delivery_time_preprocessor.pkl
models/delivery_time_linear_regression.pkl
models/delivery_time_preprocessor.pkl

=============== outputs ===============
outputs/day4_cross_validation_results.csv
outputs/day4_feature_engineered_dataset.csv
outputs/day4_feature_importance.csv
outputs/day4_final_recommendation.csv
outputs/day4_model_comparison.csv
outputs/day4_project_summary.csv
outputs/day5_adf_results.csv
outputs/day5_business_summary.csv
outputs/day5_decomposition_components.csv
outputs/day5_final_demand_forecast.csv
outputs/day5_hourly_demand.csv
outputs/day5_model_comparison.csv
outputs/day5_test_predictions.csv
outputs/day5_train_test_split.csv
outputs/visualizations/customer_complaint_categories.png
outputs/visualizations/customer_dbscan_pca.png
outputs/visualizations/customer_elbow.png
outputs/visualizations/customer_kmeans_pca.png
outputs/visualizations/day5_actual_vs_predicted.png
outputs/visualizations/day5_average_by_hour.png
outputs/visualizations/day5_decomposition.png
outputs/visualizations/day5_final_forecast.png
outputs/visualizations/day5_hourly_demand.png
outputs/visualizations/day5_train_test_split.png
outputs/visualizations/day5_weekday_weekend.png
outputs/visualizations/naive_bayes_confusion_matrix.png
outputs/visualizations/restaurant_dbscan_pca.png
outputs/visualizations/restaurant_elbow.png
outputs/visualizations/restaurant_kmeans_pca.png
outputs/visualizations/svm_confusion_matrix.png
outputs/visualizations/top_customer_complaint_words.png

=============== src ===============
src/generate_data.py
src/validate_data.py

=============== docs ===============
docs/data_dictionary.md

In [6]:
import pandas as pd
from pathlib import Path

project_path = Path.cwd().parent

files_to_check = [
    "data/processed/customer_segments.csv",
    "data/processed/restaurant_segments.csv",
    "data/processed/reviews_with_sentiment_analysis.csv",
    "data/processed/complaint_category_summary.csv",
    "data/processed/sentiment_summary.csv",
    "outputs/day4_model_comparison.csv",
    "outputs/day4_feature_importance.csv",
    "outputs/day5_model_comparison.csv",
    "outputs/day5_final_demand_forecast.csv",
    "outputs/day5_business_summary.csv"
]

for filename in files_to_check:
    file_path = project_path / filename

    print(f"\n{'=' * 60}")
    print(f"FILE: {filename}")

    if file_path.exists():
        df = pd.read_csv(file_path)

        print("Shape:", df.shape)
        print("Columns:", df.columns.tolist())
        print("\nFirst 3 rows:")
        display(df.head(3))
    else:
        print("File not found")

============================================================
FILE: data/processed/customer_segments.csv
Shape: (500, 10)
Columns: ['customer_id', 'total_orders', 'weekend_orders', 'late_night_orders', 'total_spending', 'avg_order_value', 'avg_rating_given', 'ordering_frequency', 'customer_cluster', 'customer_dbscan_cluster']

First 3 rows:

,customer_id,total_orders,weekend_orders,late_night_orders,total_spending,avg_order_value,avg_rating_given,ordering_frequency,customer_cluster,customer_dbscan_cluster
0,1,9.0,4.0,0.0,4408.20,551.0250,0.444444,1.0,0,-1
1,2,8.0,3.0,2.0,6217.58,777.1975,0.625000,1.0,0,0
2,3,6.0,0.0,0.0,3855.51,771.1020,0.333333,1.0,1,0

============================================================
FILE: data/processed/restaurant_segments.csv
Shape: (50, 12)
Columns: ['restaurant_id', 'restaurant_name', 'cuisine', 'rating', 'avg_prep_time_minutes', 'total_orders', 'cancelled_orders', 'cancellation_rate', 'total_revenue', 'avg_delivery_time', 'restaurant_cluster', 'restaurant_dbscan_cluster']

First 3 rows:

,restaurant_id,restaurant_name,cuisine,rating,avg_prep_time_minutes,total_orders,cancelled_orders,cancellation_rate,total_revenue,avg_delivery_time,restaurant_cluster,restaurant_dbscan_cluster
0,1,Restaurant_1,Indian,3.0,36,62,4,6.451613,43693.05,53.339286,0,-1
1,2,Restaurant_2,Fast Food,3.7,15,61,7,11.475410,41782.38,44.820000,0,-1
2,3,Restaurant_3,Fast Food,2.5,18,61,4,6.557377,46240.91,53.178571,0,-1

============================================================
FILE: data/processed/reviews_with_sentiment_analysis.csv
Shape: (3000, 10)
Columns: ['review_id', 'order_id', 'customer_id', 'review_text', 'sentiment', 'review_date', 'processed_review', 'vader_scores', 'vader_compound', 'vader_sentiment']

First 3 rows:

,review_id,order_id,customer_id,review_text,sentiment,review_date,processed_review,vader_scores,vader_compound,vader_sentiment
0,1,1,258,Amazing experience,Positive,2025-09-17 12:00:00,amazing experience,"{'neg': 0.0, 'neu': 0.208, 'pos': 0.792, 'comp...",0.5859,Positive
1,2,2,180,Fresh food delivered on time,Positive,2025-09-27 15:00:00,fresh food delivered time,"{'neg': 0.0, 'neu': 0.635, 'pos': 0.365, 'comp...",0.3182,Positive
2,3,3,487,Loved the food and service,Positive,2025-04-30 07:00:00,loved food service,"{'neg': 0.0, 'neu': 0.506, 'pos': 0.494, 'comp...",0.5994,Positive

============================================================
FILE: data/processed/complaint_category_summary.csv
Shape: (6, 2)
Columns: ['Complaint Category', 'Review Count']

First 3 rows:

  Complaint Category  Review Count
0       Food Quality           167
1      Late Delivery           163
2              Other           155

============================================================
FILE: data/processed/sentiment_summary.csv
Shape: (3, 3)
Columns: ['Sentiment', 'Review Count', 'Percentage']

First 3 rows:

  Sentiment  Review Count  Percentage
0  Positive          1766       58.87
1  Negative           779       25.97
2   Neutral           455       15.17

============================================================
FILE: outputs/day4_model_comparison.csv
Shape: (5, 4)
Columns: ['Model', 'MAE', 'RMSE', 'R2 Score']

First 3 rows:

               Model    MAE   RMSE  R2 Score
0  Linear Regression  20.48  23.67    0.0007
1   Ridge Regression  20.48  23.67    0.0007
2   Lasso Regression  20.49  23.68    0.0001

============================================================
FILE: outputs/day4_feature_importance.csv
Shape: (7, 2)
Columns: ['Feature', 'Importance']

First 3 rows:

               Feature  Importance
0     num__distance_km    0.797209
1    cat__traffic_High    0.038746
2  cat__traffic_Medium    0.038617

============================================================
FILE: outputs/day5_model_comparison.csv
Shape: (3, 4)
Columns: ['Model', 'MAE', 'RMSE', 'MAPE (%) for nonzero actuals']

First 3 rows:

            Model       MAE      RMSE  MAPE (%) for nonzero actuals
0  Naive baseline  0.335237  0.670416                    100.000000
1  ARIMA(1, 0, 1)  0.484906  0.580653                     68.577234
2         Prophet  0.486568  0.580639                     67.927566

============================================================
FILE: outputs/day5_final_demand_forecast.csv
Shape: (24, 3)
Columns: ['timestamp', 'forecast_orders', 'selected_model']

First 3 rows:

             timestamp  forecast_orders  selected_model
0  2025-12-31 23:00:00              1.0  Naive baseline
1  2026-01-01 00:00:00              1.0  Naive baseline
2  2026-01-01 01:00:00              1.0  Naive baseline

============================================================
FILE: outputs/day5_business_summary.csv
Shape: (1, 9)
Columns: ['average_orders_per_hour', 'peak_hour_of_day', 'average_orders_at_peak_hour', 'quietest_hour_of_day', 'average_orders_at_quietest_hour', 'best_model_by_test_MAE', 'test_MAE', 'test_RMSE', 'test_MAPE_percent_nonzero_actuals']

First 3 rows:

,average_orders_per_hour,peak_hour_of_day,average_orders_at_peak_hour,quietest_hour_of_day,average_orders_at_quietest_hour,best_model_by_test_MAE,test_MAE,test_RMSE,test_MAPE_percent_nonzero_actuals
0,0.34,02:00,0.4,06:00,0.28,Naive baseline,0.34,0.67,100.0

In [8]:
import pandas as pd
from pathlib import Path

# Set project directory
project_path = Path.cwd().parent

# Load existing processed datasets and model outputs
customer_segments = pd.read_csv(
    project_path / "data/processed/customer_segments.csv"
)

restaurant_segments = pd.read_csv(
    project_path / "data/processed/restaurant_segments.csv"
)

reviews = pd.read_csv(
    project_path / "data/processed/reviews_with_sentiment_analysis.csv"
)

complaint_summary = pd.read_csv(
    project_path / "data/processed/complaint_category_summary.csv"
)

sentiment_summary = pd.read_csv(
    project_path / "data/processed/sentiment_summary.csv"
)

delivery_model_comparison = pd.read_csv(
    project_path / "outputs/day4_model_comparison.csv"
)

delivery_feature_importance = pd.read_csv(
    project_path / "outputs/day4_feature_importance.csv"
)

demand_model_comparison = pd.read_csv(
    project_path / "outputs/day5_model_comparison.csv"
)

demand_forecast = pd.read_csv(
    project_path / "outputs/day5_final_demand_forecast.csv"
)

demand_business_summary = pd.read_csv(
    project_path / "outputs/day5_business_summary.csv"
)

# Display loaded datasets
datasets = {
    "Customer Segments": customer_segments,
    "Restaurant Segments": restaurant_segments,
    "Customer Reviews": reviews,
    "Complaint Summary": complaint_summary,
    "Sentiment Summary": sentiment_summary,
    "Delivery Model Comparison": delivery_model_comparison,
    "Delivery Feature Importance": delivery_feature_importance,
    "Demand Model Comparison": demand_model_comparison,
    "Demand Forecast": demand_forecast,
    "Demand Business Summary": demand_business_summary
}

for name, df in datasets.items():
    print(f"\n{'=' * 50}")
    print(name)
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())

==================================================
Customer Segments
Shape: (500, 10)
Columns: ['customer_id', 'total_orders', 'weekend_orders', 'late_night_orders', 'total_spending', 'avg_order_value', 'avg_rating_given', 'ordering_frequency', 'customer_cluster', 'customer_dbscan_cluster']

==================================================
Restaurant Segments
Shape: (50, 12)
Columns: ['restaurant_id', 'restaurant_name', 'cuisine', 'rating', 'avg_prep_time_minutes', 'total_orders', 'cancelled_orders', 'cancellation_rate', 'total_revenue', 'avg_delivery_time', 'restaurant_cluster', 'restaurant_dbscan_cluster']

==================================================
Customer Reviews
Shape: (3000, 10)
Columns: ['review_id', 'order_id', 'customer_id', 'review_text', 'sentiment', 'review_date', 'processed_review', 'vader_scores', 'vader_compound', 'vader_sentiment']

==================================================
Complaint Summary
Shape: (6, 2)
Columns: ['Complaint Category', 'Review Count']

==================================================
Sentiment Summary
Shape: (3, 3)
Columns: ['Sentiment', 'Review Count', 'Percentage']

==================================================
Delivery Model Comparison
Shape: (5, 4)
Columns: ['Model', 'MAE', 'RMSE', 'R2 Score']

==================================================
Delivery Feature Importance
Shape: (7, 2)
Columns: ['Feature', 'Importance']

==================================================
Demand Model Comparison
Shape: (3, 4)
Columns: ['Model', 'MAE', 'RMSE', 'MAPE (%) for nonzero actuals']

==================================================
Demand Forecast
Shape: (24, 3)
Columns: ['timestamp', 'forecast_orders', 'selected_model']

==================================================
Demand Business Summary
Shape: (1, 9)
Columns: ['average_orders_per_hour', 'peak_hour_of_day', 'average_orders_at_peak_hour', 'quietest_hour_of_day', 'average_orders_at_quietest_hour', 'best_model_by_test_MAE', 'test_MAE', 'test_RMSE', 'test_MAPE_percent_nonzero_actuals']

In [9]:
# Check missing values, duplicate rows and data types
for name, df in datasets.items():

    print(f"\n{'=' * 50}")
    print(f"DATA VALIDATION: {name}")
    print("Total Rows:", df.shape[0])
    print("Total Columns:", df.shape[1])

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:", df.duplicated().sum())

    print("\nData Types:")
    print(df.dtypes)

==================================================
DATA VALIDATION: Customer Segments
Total Rows: 500
Total Columns: 10

Missing Values:
customer_id                0
total_orders               0
weekend_orders             0
late_night_orders          0
total_spending             0
avg_order_value            0
avg_rating_given           0
ordering_frequency         0
customer_cluster           0
customer_dbscan_cluster    0
dtype: int64

Duplicate Rows: 0

Data Types:
customer_id                  int64
total_orders               float64
weekend_orders             float64
late_night_orders          float64
total_spending             float64
avg_order_value            float64
avg_rating_given           float64
ordering_frequency         float64
customer_cluster             int64
customer_dbscan_cluster      int64
dtype: object

==================================================
DATA VALIDATION: Restaurant Segments
Total Rows: 50
Total Columns: 12

Missing Values:
restaurant_id                0
restaurant_name              0
cuisine                      0
rating                       0
avg_prep_time_minutes        0
total_orders                 0
cancelled_orders             0
cancellation_rate            0
total_revenue                0
avg_delivery_time            0
restaurant_cluster           0
restaurant_dbscan_cluster    0
dtype: int64

Duplicate Rows: 0

Data Types:
restaurant_id                  int64
restaurant_name               object
cuisine                       object
rating                       float64
avg_prep_time_minutes          int64
total_orders                   int64
cancelled_orders               int64
cancellation_rate            float64
total_revenue                float64
avg_delivery_time            float64
restaurant_cluster             int64
restaurant_dbscan_cluster      int64
dtype: object

==================================================
DATA VALIDATION: Customer Reviews
Total Rows: 3000
Total Columns: 10

Missing Values:
review_id           0
order_id            0
customer_id         0
review_text         0
sentiment           0
review_date         0
processed_review    0
vader_scores        0
vader_compound      0
vader_sentiment     0
dtype: int64

Duplicate Rows: 0

Data Types:
review_id             int64
order_id              int64
customer_id           int64
review_text          object
sentiment            object
review_date          object
processed_review     object
vader_scores         object
vader_compound      float64
vader_sentiment      object
dtype: object

==================================================
DATA VALIDATION: Complaint Summary
Total Rows: 6
Total Columns: 2

Missing Values:
Complaint Category    0
Review Count          0
dtype: int64

Duplicate Rows: 0

Data Types:
Complaint Category    object
Review Count           int64
dtype: object

==================================================
DATA VALIDATION: Sentiment Summary
Total Rows: 3
Total Columns: 3

Missing Values:
Sentiment       0
Review Count    0
Percentage      0
dtype: int64

Duplicate Rows: 0

Data Types:
Sentiment        object
Review Count      int64
Percentage      float64
dtype: object

==================================================
DATA VALIDATION: Delivery Model Comparison
Total Rows: 5
Total Columns: 4

Missing Values:
Model       0
MAE         0
RMSE        0
R2 Score    0
dtype: int64

Duplicate Rows: 0

Data Types:
Model        object
MAE         float64
RMSE        float64
R2 Score    float64
dtype: object

==================================================
DATA VALIDATION: Delivery Feature Importance
Total Rows: 7
Total Columns: 2

Missing Values:
Feature       0
Importance    0
dtype: int64

Duplicate Rows: 0

Data Types:
Feature        object
Importance    float64
dtype: object

==================================================
DATA VALIDATION: Demand Model Comparison
Total Rows: 3
Total Columns: 4

Missing Values:
Model                           0
MAE                             0
RMSE                            0
MAPE (%) for nonzero actuals    0
dtype: int64

Duplicate Rows: 0

Data Types:
Model                            object
MAE                             float64
RMSE                            float64
MAPE (%) for nonzero actuals    float64
dtype: object

==================================================
DATA VALIDATION: Demand Forecast
Total Rows: 24
Total Columns: 3

Missing Values:
timestamp          0
forecast_orders    0
selected_model     0
dtype: int64

Duplicate Rows: 0

Data Types:
timestamp           object
forecast_orders    float64
selected_model      object
dtype: object

==================================================
DATA VALIDATION: Demand Business Summary
Total Rows: 1
Total Columns: 9

Missing Values:
average_orders_per_hour              0
peak_hour_of_day                     0
average_orders_at_peak_hour          0
quietest_hour_of_day                 0
average_orders_at_quietest_hour      0
best_model_by_test_MAE               0
test_MAE                             0
test_RMSE                            0
test_MAPE_percent_nonzero_actuals    0
dtype: int64

Duplicate Rows: 0

Data Types:
average_orders_per_hour              float64
peak_hour_of_day                      object
average_orders_at_peak_hour          float64
quietest_hour_of_day                  object
average_orders_at_quietest_hour      float64
best_model_by_test_MAE                object
test_MAE                             float64
test_RMSE                            float64
test_MAPE_percent_nonzero_actuals    float64
dtype: object

In [10]:
# Inspect raw datasets for tip and location-related columns

raw_files = [
    "customers.csv",
    "orders.csv",
    "payments.csv",
    "deliveries.csv",
    "restaurants.csv",
    "drivers.csv",
    "reviews.csv"
]

for filename in raw_files:

    file_path = project_path / "data/raw" / filename

    print(f"\n{'=' * 50}")
    print("FILE:", filename)

    if file_path.exists():
        df = pd.read_csv(file_path)

        print("Shape:", df.shape)
        print("Columns:", df.columns.tolist())

        relevant_columns = [
            col for col in df.columns
            if any(word in col.lower() for word in
                   ["tip", "location", "city", "area", "address",
                    "latitude", "longitude", "date", "time"])
        ]

        print("Relevant Columns:", relevant_columns)

    else:
        print("File not found")

==================================================
FILE: customers.csv
Shape: (500, 4)
Columns: ['customer_id', 'age', 'city', 'signup_date']
Relevant Columns: ['city', 'signup_date']

==================================================
FILE: orders.csv
Shape: (3000, 6)
Columns: ['order_id', 'customer_id', 'restaurant_id', 'order_timestamp', 'order_amount', 'order_status']
Relevant Columns: ['order_timestamp']

==================================================
FILE: payments.csv
Shape: (3000, 5)
Columns: ['payment_id', 'order_id', 'payment_method', 'tip_amount', 'payment_status']
Relevant Columns: ['tip_amount']

==================================================
FILE: deliveries.csv
Shape: (3000, 7)
Columns: ['delivery_id', 'order_id', 'driver_id', 'distance_km', 'delivery_time_minutes', 'weather', 'traffic']
Relevant Columns: ['delivery_time_minutes']

==================================================
FILE: restaurants.csv
Shape: (50, 5)
Columns: ['restaurant_id', 'restaurant_name', 'cuisine', 'rating', 'avg_prep_time_minutes']
Relevant Columns: ['avg_prep_time_minutes']

==================================================
FILE: drivers.csv
Shape: (100, 3)
Columns: ['driver_id', 'experience_years', 'driver_rating']
Relevant Columns: []

==================================================
FILE: reviews.csv
Shape: (3000, 6)
Columns: ['review_id', 'order_id', 'customer_id', 'review_text', 'sentiment', 'review_date']
Relevant Columns: ['sentiment', 'review_date']

In [11]:
# Load raw datasets
customers = pd.read_csv(project_path / "data/raw/customers.csv")
orders = pd.read_csv(project_path / "data/raw/orders.csv")
payments = pd.read_csv(project_path / "data/raw/payments.csv")
deliveries = pd.read_csv(project_path / "data/raw/deliveries.csv")
restaurants = pd.read_csv(project_path / "data/raw/restaurants.csv")

# Inspect important columns and sample records
raw_datasets = {
    "Customers": customers,
    "Orders": orders,
    "Payments": payments,
    "Deliveries": deliveries,
    "Restaurants": restaurants
}

for name, df in raw_datasets.items():
    print(f"\n{'=' * 50}")
    print(name)
    print("Columns:", df.columns.tolist())
    display(df.head(3))

# Check tip amount details
print("\nTIP AMOUNT SUMMARY")
print(payments["tip_amount"].describe())

print("\nMissing tip values:", payments["tip_amount"].isnull().sum())
print("Zero tip values:", (payments["tip_amount"] == 0).sum())

==================================================
Customers
Columns: ['customer_id', 'age', 'city', 'signup_date']

   customer_id  age       city signup_date
0            1   56  Bengaluru  2025-10-03
1            2   46      Delhi  2024-05-17
2            3   32  Hyderabad  2025-03-31

==================================================
Orders
Columns: ['order_id', 'customer_id', 'restaurant_id', 'order_timestamp', 'order_amount', 'order_status']

,order_id,customer_id,restaurant_id,order_timestamp,order_amount,order_status
0,1,258,37,2025-09-17 12:00:00,891.05,Delivered
1,2,180,19,2025-09-27 15:00:00,1037.56,Delivered
2,3,487,33,2025-04-30 07:00:00,1445.94,Delivered

==================================================
Payments
Columns: ['payment_id', 'order_id', 'payment_method', 'tip_amount', 'payment_status']

   payment_id  order_id payment_method  tip_amount payment_status
0           1         1           Card      130.37     Successful
1           2         2           Cash       30.60     Successful
2           3         3           Card       94.44     Successful

==================================================
Deliveries
Columns: ['delivery_id', 'order_id', 'driver_id', 'distance_km', 'delivery_time_minutes', 'weather', 'traffic']

,delivery_id,order_id,driver_id,distance_km,delivery_time_minutes,weather,traffic
0,1,1,42,10.82,57,Rainy,Low
1,2,2,95,3.74,19,Cloudy,Low
2,3,3,50,12.82,90,Clear,High

==================================================
Restaurants
Columns: ['restaurant_id', 'restaurant_name', 'cuisine', 'rating', 'avg_prep_time_minutes']

   restaurant_id restaurant_name    cuisine  rating  avg_prep_time_minutes
0              1    Restaurant_1     Indian     3.0                     36
1              2    Restaurant_2  Fast Food     3.7                     15
2              3    Restaurant_3  Fast Food     2.5                     18

TIP AMOUNT SUMMARY
count    3000.000000
mean       99.727330
std        57.086211
min         0.000000
25%        50.507500
50%       100.845000
75%       147.080000
max       199.960000
Name: tip_amount, dtype: float64

Missing tip values: 0
Zero tip values: 1

In [12]:
# Merge customer, order, payment and delivery information

integrated_data = orders.merge(
    customers,
    on="customer_id",
    how="left"
)

integrated_data = integrated_data.merge(
    payments,
    on="order_id",
    how="left"
)

integrated_data = integrated_data.merge(
    deliveries,
    on="order_id",
    how="left"
)

# Display integrated dataset
print("Integrated Dataset Shape:", integrated_data.shape)
print("\nColumns:", integrated_data.columns.tolist())

display(integrated_data.head())

Integrated Dataset Shape: (3000, 19)

Columns: ['order_id', 'customer_id', 'restaurant_id', 'order_timestamp', 'order_amount', 'order_status', 'age', 'city', 'signup_date', 'payment_id', 'payment_method', 'tip_amount', 'payment_status', 'delivery_id', 'driver_id', 'distance_km', 'delivery_time_minutes', 'weather', 'traffic']

,order_id,customer_id,restaurant_id,order_timestamp,order_amount,order_status,age,city,signup_date,payment_id,payment_method,tip_amount,payment_status,delivery_id,driver_id,distance_km,delivery_time_minutes,weather,traffic
0,1,258,37,2025-09-17 12:00:00,891.05,Delivered,48,Chennai,2023-03-02,1,Card,130.37,Successful,1,42,10.82,57,Rainy,Low
1,2,180,19,2025-09-27 15:00:00,1037.56,Delivered,18,Mumbai,2023-09-18,2,Cash,30.60,Successful,2,95,3.74,19,Cloudy,Low
2,3,487,33,2025-04-30 07:00:00,1445.94,Delivered,62,Chennai,2024-01-16,3,Card,94.44,Successful,3,50,12.82,90,Clear,High
3,4,373,47,2025-02-19 01:00:00,943.74,Delivered,50,Bengaluru,2025-07-25,4,Card,18.87,Successful,4,60,9.78,39,Cloudy,High
4,5,172,16,2025-07-18 08:00:00,883.27,Delivered,61,Bengaluru,2024-05-28,5,Cash,120.42,Successful,5,1,18.78,44,Rainy,Medium

In [13]:
print("Integrated Dataset Information:")
integrated_data.info()

print("\nMissing Values:")
print(integrated_data.isnull().sum())

print("\nDuplicate Rows:")
print(integrated_data.duplicated().sum())

Integrated Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               3000 non-null   int64
 1   customer_id            3000 non-null   int64
 2   restaurant_id          3000 non-null   int64
 3   order_timestamp        3000 non-null   object
 4   order_amount           3000 non-null   float64
 5   order_status           3000 non-null   object
 6   age                    3000 non-null   int64
 7   city                   3000 non-null   object
 8   signup_date            3000 non-null   object
 9   payment_id             3000 non-null   int64
 10  payment_method         3000 non-null   object
 11  tip_amount             3000 non-null   float64
 12  payment_status         3000 non-null   object
 13  delivery_id            3000 non-null   int64
 14  driver_id              3000 non-null   int64
 15  distance_km            3000 non-null   float64
 16  delivery_time_minutes  3000 non-null   int64
 17  weather                3000 non-null   object
 18  traffic                3000 non-null   object
dtypes: float64(3), int64(8), object(8)
memory usage: 445.4+ KB

Missing Values:
order_id                 0
customer_id              0
restaurant_id            0
order_timestamp          0
order_amount             0
order_status             0
age                      0
city                     0
signup_date              0
payment_id               0
payment_method           0
tip_amount               0
payment_status           0
delivery_id              0
driver_id                0
distance_km              0
delivery_time_minutes    0
weather                  0
traffic                  0
dtype: int64

Duplicate Rows:
0

In [14]:
# Integrate customer segmentation results

integrated_data = integrated_data.merge(
    customer_segments[["customer_id", "customer_cluster", "customer_dbscan_cluster"]],
    on="customer_id",
    how="left"
)

# Integrate restaurant segmentation results

integrated_data = integrated_data.merge(
    restaurant_segments[["restaurant_id", "restaurant_cluster", "restaurant_dbscan_cluster"]],
    on="restaurant_id",
    how="left"
)

# Validate segmentation integration

print("Updated Integrated Dataset Shape:", integrated_data.shape)

print("\nMissing Values in Cluster Columns:")
print(
    integrated_data[
        [
            "customer_cluster",
            "customer_dbscan_cluster",
            "restaurant_cluster",
            "restaurant_dbscan_cluster"
        ]
    ].isnull().sum()
)

display(integrated_data.head())

Updated Integrated Dataset Shape: (3000, 23)

Missing Values in Cluster Columns:
customer_cluster             0
customer_dbscan_cluster      0
restaurant_cluster           0
restaurant_dbscan_cluster    0
dtype: int64

,order_id,customer_id,restaurant_id,order_timestamp,order_amount,order_status,age,city,signup_date,payment_id,...,delivery_id,driver_id,distance_km,delivery_time_minutes,weather,traffic,customer_cluster,customer_dbscan_cluster,restaurant_cluster,restaurant_dbscan_cluster
0,1,258,37,2025-09-17 12:00:00,891.05,Delivered,48,Chennai,2023-03-02,1,...,1,42,10.82,57,Rainy,Low,0,0,0,3
1,2,180,19,2025-09-27 15:00:00,1037.56,Delivered,18,Mumbai,2023-09-18,2,...,2,95,3.74,19,Cloudy,Low,0,0,0,-1
2,3,487,33,2025-04-30 07:00:00,1445.94,Delivered,62,Chennai,2024-01-16,3,...,3,50,12.82,90,Clear,High,0,0,0,-1
3,4,373,47,2025-02-19 01:00:00,943.74,Delivered,50,Bengaluru,2025-07-25,4,...,4,60,9.78,39,Cloudy,High,0,-1,1,1
4,5,172,16,2025-07-18 08:00:00,883.27,Delivered,61,Bengaluru,2024-05-28,5,...,5,1,18.78,44,Rainy,Medium,0,0,0,-1

In [15]:
# Select relevant sentiment columns
sentiment_data = reviews[
    ["order_id", "sentiment"]
].copy()

# Merge sentiment results with integrated dataset
integrated_data = integrated_data.merge(
    sentiment_data,
    on="order_id",
    how="left"
)

# Validate sentiment integration
print("Updated Integrated Dataset Shape:", integrated_data.shape)

print("\nMissing Sentiment Values:")
print(integrated_data["sentiment"].isnull().sum())

print("\nSentiment Distribution:")
print(integrated_data["sentiment"].value_counts())

display(integrated_data.head())

Updated Integrated Dataset Shape: (3000, 24)

Missing Sentiment Values:
0

Sentiment Distribution:
sentiment
Positive    1766
Negative     779
Neutral      455
Name: count, dtype: int64

,order_id,customer_id,restaurant_id,order_timestamp,order_amount,order_status,age,city,signup_date,payment_id,...,driver_id,distance_km,delivery_time_minutes,weather,traffic,customer_cluster,customer_dbscan_cluster,restaurant_cluster,restaurant_dbscan_cluster,sentiment
0,1,258,37,2025-09-17 12:00:00,891.05,Delivered,48,Chennai,2023-03-02,1,...,42,10.82,57,Rainy,Low,0,0,0,3,Positive
1,2,180,19,2025-09-27 15:00:00,1037.56,Delivered,18,Mumbai,2023-09-18,2,...,95,3.74,19,Cloudy,Low,0,0,0,-1,Positive
2,3,487,33,2025-04-30 07:00:00,1445.94,Delivered,62,Chennai,2024-01-16,3,...,50,12.82,90,Clear,High,0,0,0,-1,Positive
3,4,373,47,2025-02-19 01:00:00,943.74,Delivered,50,Bengaluru,2025-07-25,4,...,60,9.78,39,Cloudy,High,0,-1,1,1,Negative
4,5,172,16,2025-07-18 08:00:00,883.27,Delivered,61,Bengaluru,2024-05-28,5,...,1,18.78,44,Rainy,Medium,0,0,0,-1,Negative

In [16]:
# Review Day 4 delivery-time model comparison

print("DELIVERY TIME MODEL COMPARISON")
display(delivery_model_comparison)

# Review important delivery-time features

print("\nDELIVERY TIME FEATURE IMPORTANCE")
display(delivery_feature_importance)

# Load the saved best-performing model
import joblib

best_delivery_model = joblib.load(
    project_path / "models/day4_best_delivery_time_model.pkl"
)

delivery_preprocessor = joblib.load(
    project_path / "models/day4_delivery_time_preprocessor.pkl"
)

print("\nSaved delivery-time model and preprocessor loaded successfully.")

DELIVERY TIME MODEL COMPARISON

               Model    MAE   RMSE  R2 Score
0  Linear Regression  20.48  23.67    0.0007
1   Ridge Regression  20.48  23.67    0.0007
2   Lasso Regression  20.49  23.68    0.0001
3  Gradient Boosting  20.79  24.11   -0.0366
4      Random Forest  22.29  26.84   -0.2841

DELIVERY TIME FEATURE IMPORTANCE

               Feature  Importance
0     num__distance_km    0.797209
1    cat__traffic_High    0.038746
2  cat__traffic_Medium    0.038617
3     cat__traffic_Low    0.037078
4   cat__weather_Clear    0.031902
5   cat__weather_Rainy    0.030562
6  cat__weather_Cloudy    0.025887

Saved delivery-time model and preprocessor loaded successfully.

In [17]:
# Review Day 5 demand forecasting model comparison

print("DEMAND FORECAST MODEL COMPARISON")
display(demand_model_comparison)

# Review final demand forecast

print("\nFINAL DEMAND FORECAST")
display(demand_forecast.head(10))

# Review demand forecasting business summary

print("\nDEMAND FORECAST BUSINESS SUMMARY")
display(demand_business_summary)

print("\nDay 5 demand forecasting outputs reviewed successfully.")

DEMAND FORECAST MODEL COMPARISON

            Model       MAE      RMSE  MAPE (%) for nonzero actuals
0  Naive baseline  0.335237  0.670416                    100.000000
1  ARIMA(1, 0, 1)  0.484906  0.580653                     68.577234
2         Prophet  0.486568  0.580639                     67.927566

FINAL DEMAND FORECAST

             timestamp  forecast_orders  selected_model
0  2025-12-31 23:00:00              1.0  Naive baseline
1  2026-01-01 00:00:00              1.0  Naive baseline
2  2026-01-01 01:00:00              1.0  Naive baseline
3  2026-01-01 02:00:00              1.0  Naive baseline
4  2026-01-01 03:00:00              1.0  Naive baseline
5  2026-01-01 04:00:00              1.0  Naive baseline
6  2026-01-01 05:00:00              1.0  Naive baseline
7  2026-01-01 06:00:00              1.0  Naive baseline
8  2026-01-01 07:00:00              1.0  Naive baseline
9  2026-01-01 08:00:00              1.0  Naive baseline

DEMAND FORECAST BUSINESS SUMMARY

,average_orders_per_hour,peak_hour_of_day,average_orders_at_peak_hour,quietest_hour_of_day,average_orders_at_quietest_hour,best_model_by_test_MAE,test_MAE,test_RMSE,test_MAPE_percent_nonzero_actuals
0,0.34,02:00,0.4,06:00,0.28,Naive baseline,0.34,0.67,100.0

Day 5 demand forecasting outputs reviewed successfully.

In [18]:
# Convert order timestamp to datetime
integrated_data["order_timestamp"] = pd.to_datetime(
    integrated_data["order_timestamp"]
)

# Extract hour and date
integrated_data["order_hour"] = (
    integrated_data["order_timestamp"].dt.hour
)

integrated_data["order_date"] = (
    integrated_data["order_timestamp"].dt.date
)

# Analyze demand by city and hour
city_hourly_demand = (
    integrated_data
    .groupby(["city", "order_hour"])
    .size()
    .reset_index(name="total_orders")
)

# Display highest-demand city and hour combinations
city_hourly_demand = city_hourly_demand.sort_values(
    "total_orders",
    ascending=False
)

print("Top 10 City-Hour Demand Combinations:")
display(city_hourly_demand.head(10))

Top 10 City-Hour Demand Combinations:

         city  order_hour  total_orders
2   Bengaluru           2            40
50      Delhi           2            34
55      Delhi           7            34
3   Bengaluru           3            33
75  Hyderabad           3            33
21  Bengaluru          21            32
8   Bengaluru           8            32
46    Chennai          22            32
64      Delhi          16            32
72  Hyderabad           0            32

In [19]:
# Analyze average tip amount by payment method
tip_by_payment = (
    integrated_data
    .groupby("payment_method")["tip_amount"]
    .agg(["mean", "count"])
    .reset_index()
)

tip_by_payment.columns = [
    "payment_method",
    "average_tip",
    "total_orders"
]

print("Average Tip by Payment Method:")
display(tip_by_payment)

# Analyze average tip amount by delivery conditions
tip_by_conditions = (
    integrated_data
    .groupby(["weather", "traffic"])["tip_amount"]
    .mean()
    .reset_index(name="average_tip")
)

print("\nAverage Tip by Weather and Traffic:")
display(tip_by_conditions)

# Analyze relationship between tip and numerical variables
print("\nCorrelation with Tip Amount:")
display(
    integrated_data[
        ["tip_amount", "order_amount", "distance_km",
         "delivery_time_minutes", "age"]
    ].corr()["tip_amount"].sort_values(ascending=False)
)

Average Tip by Payment Method:

  payment_method  average_tip  total_orders
0           Card    99.001882           781
1           Cash    99.448379           728
2            UPI    97.795774           717
3         Wallet   102.511021           774

Average Tip by Weather and Traffic:

  weather traffic  average_tip
0   Clear    High    97.237112
1   Clear     Low   104.249744
2   Clear  Medium   100.332288
3  Cloudy    High   100.342232
4  Cloudy     Low    99.715273
5  Cloudy  Medium    98.248000
6   Rainy    High    96.070494
7   Rainy     Low   100.831303
8   Rainy  Medium   100.460852

Correlation with Tip Amount:

tip_amount               1.000000
age                      0.031614
order_amount             0.019924
delivery_time_minutes   -0.016442
distance_km             -0.045716
Name: tip_amount, dtype: float64

In [20]:
model_comparison = pd.DataFrame([
    {
        "Component": "Customer Segmentation",
        "Model": "K-Means / DBSCAN",
        "Evaluation": "Silhouette Score",
        "Result": "Refer to Day 2 evaluation"
    },
    {
        "Component": "Restaurant Segmentation",
        "Model": "K-Means / DBSCAN",
        "Evaluation": "Silhouette Score",
        "Result": "Refer to Day 2 evaluation"
    },
    {
        "Component": "Sentiment Analysis",
        "Model": "Naive Bayes / SVM",
        "Evaluation": "Accuracy",
        "Result": "1.0 for both models"
    },
    {
        "Component": "Delivery Time Prediction",
        "Model": "Linear Regression",
        "Evaluation": "MAE / RMSE / R2",
        "Result": "20.48 / 23.67 / 0.0007"
    },
    {
        "Component": "Demand Forecasting",
        "Model": "Naive Baseline",
        "Evaluation": "Test MAE / RMSE",
        "Result": "0.34 / 0.67"
    }
])

print("INTEGRATED MODEL COMPARISON SUMMARY")
display(model_comparison)

INTEGRATED MODEL COMPARISON SUMMARY

,Component,Model,Evaluation,Result
0,Customer Segmentation,K-Means / DBSCAN,Silhouette Score,Refer to Day 2 evaluation
1,Restaurant Segmentation,K-Means / DBSCAN,Silhouette Score,Refer to Day 2 evaluation
2,Sentiment Analysis,Naive Bayes / SVM,Accuracy,1.0 for both models
3,Delivery Time Prediction,Linear Regression,MAE / RMSE / R2,20.48 / 23.67 / 0.0007
4,Demand Forecasting,Naive Baseline,Test MAE / RMSE,0.34 / 0.67

In [21]:
business_insights = pd.DataFrame([
    {
        "Business Area": "Customer Segmentation",
        "Key Finding": "Customers are grouped into distinct segments using K-Means and DBSCAN.",
        "Business Insight": "Customer segments can be used to identify valuable customer groups and improve retention strategies."
    },
    {
        "Business Area": "Restaurant Segmentation",
        "Key Finding": "Restaurants are grouped based on their operational characteristics.",
        "Business Insight": "Restaurant segments can help identify businesses that require operational improvement."
    },
    {
        "Business Area": "Customer Sentiment",
        "Key Finding": "Customer reviews contain positive, negative and neutral feedback.",
        "Business Insight": "Negative sentiment and complaint categories can help identify areas affecting customer satisfaction."
    },
    {
        "Business Area": "Delivery Time",
        "Key Finding": "Distance is the most important feature, with an importance score of approximately 0.797.",
        "Business Insight": "Delivery distance should be considered when planning delivery operations. The prediction model has limited explanatory power."
    },
    {
        "Business Area": "Demand Forecasting",
        "Key Finding": "The historical peak hour is 02:00, while the quietest hour is 06:00.",
        "Business Insight": "Demand patterns can support hourly delivery-capacity planning. Forecast accuracy limitations should be considered."
    },
    {
        "Business Area": "Tip Analysis",
        "Key Finding": "Wallet payments have the highest average tip, approximately 102.51.",
        "Business Insight": "Payment method and delivery conditions show differences in average tip amounts, although observed correlations are weak."
    },
    {
        "Business Area": "Location-Based Demand",
        "Key Finding": "Bengaluru recorded 40 orders at 02:00 in the historical city-hour analysis.",
        "Business Insight": "Historical city-hour demand can help identify periods for closer capacity monitoring."
    }
])

print("DAY 6 BUSINESS INSIGHTS")
display(business_insights)

DAY 6 BUSINESS INSIGHTS

,Business Area,Key Finding,Business Insight
0,Customer Segmentation,Customers are grouped into distinct segments u...,Customer segments can be used to identify valu...
1,Restaurant Segmentation,Restaurants are grouped based on their operati...,Restaurant segments can help identify business...
2,Customer Sentiment,"Customer reviews contain positive, negative an...",Negative sentiment and complaint categories ca...
3,Delivery Time,"Distance is the most important feature, with a...",Delivery distance should be considered when pl...
4,Demand Forecasting,"The historical peak hour is 02:00, while the q...",Demand patterns can support hourly delivery-ca...
5,Tip Analysis,"Wallet payments have the highest average tip, ...",Payment method and delivery conditions show di...
6,Location-Based Demand,Bengaluru recorded 40 orders at 02:00 in the h...,Historical city-hour demand can help identify ...

In [22]:
business_recommendations = pd.DataFrame([
    {
        "Business Area": "Customer Segmentation",
        "Recommendation": "Develop targeted retention and engagement strategies for valuable customer segments."
    },
    {
        "Business Area": "Restaurant Segmentation",
        "Recommendation": "Identify underperforming restaurant segments and provide operational support."
    },
    {
        "Business Area": "Customer Sentiment",
        "Recommendation": "Address recurring customer complaints and improve service quality."
    },
    {
        "Business Area": "Delivery Time",
        "Recommendation": "Consider delivery distance, traffic and weather when planning delivery operations."
    },
    {
        "Business Area": "Demand Forecasting",
        "Recommendation": "Use forecasted demand patterns to plan delivery-partner availability during peak hours."
    },
    {
        "Business Area": "Tip Analysis",
        "Recommendation": "Monitor tip patterns across payment methods and delivery conditions without assuming causation."
    },
    {
        "Business Area": "Location-Based Demand",
        "Recommendation": "Monitor city-wise hourly demand to support location-specific delivery-capacity planning."
    }
])

print("DAY 6 BUSINESS RECOMMENDATIONS")
display(business_recommendations)

DAY 6 BUSINESS RECOMMENDATIONS

             Business Area                                     Recommendation
0    Customer Segmentation  Develop targeted retention and engagement stra...
1  Restaurant Segmentation  Identify underperforming restaurant segments a...
2       Customer Sentiment  Address recurring customer complaints and impr...
3            Delivery Time  Consider delivery distance, traffic and weathe...
4       Demand Forecasting  Use forecasted demand patterns to plan deliver...
5             Tip Analysis  Monitor tip patterns across payment methods an...
6    Location-Based Demand  Monitor city-wise hourly demand to support loc...

In [23]:
model_limitations = pd.DataFrame([
    {
        "Component": "Customer Segmentation",
        "Limitation": "Clustering results depend on selected features, scaling and cluster parameters."
    },
    {
        "Component": "Restaurant Segmentation",
        "Limitation": "Cluster quality depends on the available restaurant features and clustering parameters."
    },
    {
        "Component": "Sentiment Analysis",
        "Limitation": "The reported perfect evaluation scores should be interpreted cautiously and may not reflect performance on unseen reviews."
    },
    {
        "Component": "Delivery Time Prediction",
        "Limitation": "The best model has an R2 score close to zero, indicating very limited explanatory power."
    },
    {
        "Component": "Demand Forecasting",
        "Limitation": "The Naive baseline performed best, and the reported MAPE of 100% indicates poor percentage-based forecast accuracy."
    },
    {
        "Component": "Tip Analysis",
        "Limitation": "The observed correlations with numerical variables are weak and do not establish causal relationships."
    },
    {
        "Component": "Location-Based Demand",
        "Limitation": "Historical city-wise hourly order counts do not guarantee future demand patterns."
    }
])

print("DAY 6 MODEL LIMITATIONS")
display(model_limitations)

DAY 6 MODEL LIMITATIONS

                  Component                                         Limitation
0     Customer Segmentation  Clustering results depend on selected features...
1   Restaurant Segmentation  Cluster quality depends on the available resta...
2        Sentiment Analysis  The reported perfect evaluation scores should ...
3  Delivery Time Prediction  The best model has an R2 score close to zero, ...
4        Demand Forecasting  The Naive baseline performed best, and the rep...
5              Tip Analysis  The observed correlations with numerical varia...
6     Location-Based Demand  Historical city-wise hourly order counts do no...

In [24]:
future_improvements = pd.DataFrame([
    {
        "Component": "Customer Segmentation",
        "Future Improvement": "Experiment with additional customer behaviour features and optimize clustering parameters."
    },
    {
        "Component": "Restaurant Segmentation",
        "Future Improvement": "Include additional restaurant performance indicators to improve segment quality."
    },
    {
        "Component": "Sentiment Analysis",
        "Future Improvement": "Evaluate models on independent review data and explore additional NLP techniques."
    },
    {
        "Component": "Delivery Time Prediction",
        "Future Improvement": "Include additional delivery-related features and experiment with improved prediction models."
    },
    {
        "Component": "Demand Forecasting",
        "Future Improvement": "Collect more historical demand data and improve forecasting model performance."
    },
    {
        "Component": "Tip Analysis",
        "Future Improvement": "Include additional payment and order-related features to better understand tipping patterns."
    },
    {
        "Component": "Location-Based Demand",
        "Future Improvement": "Collect more detailed location-wise order data to improve demand planning."
    }
])

print("DAY 6 FUTURE IMPROVEMENTS")
display(future_improvements)

DAY 6 FUTURE IMPROVEMENTS

                  Component                                 Future Improvement
0     Customer Segmentation  Experiment with additional customer behaviour ...
1   Restaurant Segmentation  Include additional restaurant performance indi...
2        Sentiment Analysis  Evaluate models on independent review data and...
3  Delivery Time Prediction  Include additional delivery-related features a...
4        Demand Forecasting  Collect more historical demand data and improv...
5              Tip Analysis  Include additional payment and order-related f...
6     Location-Based Demand  Collect more detailed location-wise order data...

In [25]:
output_path = project_path / "outputs"
output_path.mkdir(parents=True, exist_ok=True)

model_comparison.to_csv(output_path / "day6_model_comparison.csv", index=False)
business_insights.to_csv(output_path / "day6_business_insights.csv", index=False)
business_recommendations.to_csv(output_path / "day6_business_recommendations.csv", index=False)
model_limitations.to_csv(output_path / "day6_model_limitations.csv", index=False)
future_improvements.to_csv(output_path / "day6_future_improvements.csv", index=False)

integrated_data.to_csv(
    project_path / "data/processed/day6_integrated_dataset.csv",
    index=False
)

print("Day 6 deliverables saved successfully!")

Day 6 deliverables saved successfully!